AWSTemplateFormatVersion: '2010-09-09'
Description: This stack creates a ECR repository.
Metadata:
  License: Apache-2.0

Parameters:
  Name:
    Type: String
    Description: A name of ECR repository to create.

Resources:
  ECR:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref Name
